# Generated by Django 5.0.3 on 2024-04-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EUDRFarmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('farm_size', models.FloatField()),
                ('collection_site', models.CharField(max_length=255)),
                ('farm_village', models.CharField(max_length=255)),
                ('farm_coordinates', models.JSONField()),
                ('farm_polygon_coordinates', models.JSONField()),
                ('plantation_name', models.CharField(max_length=255)),
                ('plantation_code', models.CharField(max_length=255)),
                ('is_validated', models.BooleanField()),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
