# Generated by Django 5.0.3 on 2024-04-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='is_eudr_compliant',
            field=models.BooleanField(default=False),
        ),
    ]
