name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DJANGO_SETTINGS_MODULE: eudr_backend.settings

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply Migrations
        run: python manage.py migrate

      - name: Run Unit Tests
        run: python manage.py test

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        env:
            AGSTACK_API_EMAIL: ${{ secrets.AGSTACK_API_EMAIL }}
            AGSTACK_API_PASSWORD: ${{ secrets.AGSTACK_API_EMAIL }}
            EMAIL_HOST_USER: ${{ secrets.AGSTACK_API_EMAIL }}
            EMAIL_HOST_PASSWORD: ${{ secrets.AGSTACK_API_EMAIL }}
            EMAIL_HOST_DEFAULT_USER: ${{ secrets.AGSTACK_API_EMAIL }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AGSTACK_API_EMAIL }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AGSTACK_API_EMAIL }}
            AWS_STORAGE_BUCKET_NAME: ${{ secrets.AGSTACK_API_EMAIL }}
            AWS_S3_REGION_NAME: ${{ secrets.AGSTACK_API_EMAIL }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
            cd TerraTrac-Validation-Portal/
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            systemctl restart gunicorn
          EOF
